### ISSUE TITLE
Font loading is done via http

### ISSUE THREAD

**Issue by Freezzz** [invertase/angular-toasty#27]
Roboto Google font is loaded via http, that can cause browser error in case site uses https.
Consider changing
```
http://fonts.gstatic.com/s/roboto/v15/zN7GBFwfMP4uA6AR0HCoLQ.ttf
```
to
```
//fonts.gstatic.com/s/roboto/v15/zN7GBFwfMP4uA6AR0HCoLQ.ttf 
```

**Comment by Ehesp** [comment]
https://github.com/invertase/angular-toasty/commit/be49d066bced8d7e40efb02acc2290c2569b45ad

Was having issues with LESS compiling when the url has no protocol and not sure why. Changed it to use HTTPS right now.

**Comment by Freezzz** [comment]
Awesome, thanks for your effort!
