### ISSUE TITLE
Request: Add type override

### ISSUE THREAD

**Issue by Fossil01** [invertase/angular-toasty#32]
Please add a type override to the default toasty() function.

That way I can do something like this without creating 5 different functions:

````javascript
  function showToast(type,title,message) {
    toasty({
      title: title,
      msg: message,
      sound: true,
      type: type
    });
  }

showToast("warning","Error: ","Something went wrong!");
````

**Comment by Ehesp** [comment]
Yep I can do that. Will look into it.

Although above you could do something like:

```
  function showToast(type,title,message) {
    toasty[type]({
      title: title,
      msg: message,
      sound: true
    });
  }

showToast("warning","Error: ","Something went wrong!");
```

Also works with [default](https://github.com/invertase/angular-toasty/blob/master/dist/angular-toasty.js#L264).

**Comment by Fossil01** [comment]
Ah so thats how to do it. I just did toasty.type which of course did not work.

**Comment by Ehesp** [comment]
Yep :)

Not tested, but you might be able to do this to handle no types:

```
  function showToast(title, message, type) {
    toasty[type || 'default']({
      title: title,
      msg: message,
      sound: true
    });
  }

showToast("Error: ","Something went wrong!");
showToast("Error: ","Something went wrong!", "warning");
```

**Comment by Fossil01** [comment]
Yeah that works.

**Comment by Ehesp** [comment]
Okay cool - will close this off, doing this is a better way than as a property IMO.
