### ISSUE TITLE
Position should allow centering

### ISSUE THREAD

**Issue by jancel** [invertase/angular-toasty#34]
Currently position only allows 4 configurations.

* position: 'bottom-right', // {string:bottom-right,bottom-left,top-right,top-left} The window position where the toast pops up

Is there any plans of adding 'bottom-center' and 'top-center'?

**Comment by Ehesp** [comment]
I can look into this, shouldn't be too hard.

**Comment by Ehesp** [comment]
Added in 1.0.5

https://github.com/invertase/angular-toasty/commit/a8841b9937537c3e3dc839cafdad7d747a624dd2
